import { CountriesAlpha3, CountriesFullName } from "./types"
import { CurrenciesEnum } from "../currencies/types"

export const validCountries: {
  [key: string]: {
    alpha2: string
    alpha3: string
    currency: string[]
    name: string
  }
} = {
  [CountriesAlpha3.ABW]: {
    alpha3: CountriesAlpha3.ABW,
    alpha2: CountriesAlpha3.ABW,
    currency: [CurrenciesEnum.AWG],
    name: CountriesFullName.ABW,
  },
  [CountriesAlpha3.AFG]: {
    alpha3: CountriesAlpha3.AFG,
    alpha2: CountriesAlpha3.AFG,
    currency: [CurrenciesEnum.AFN],
    name: CountriesFullName.AFG,
  },
  [CountriesAlpha3.AGO]: {
    alpha3: CountriesAlpha3.AGO,
    alpha2: CountriesAlpha3.AGO,
    currency: [CurrenciesEnum.AOA],
    name: CountriesFullName.AGO,
  },
  [CountriesAlpha3.AIA]: {
    alpha3: CountriesAlpha3.AIA,
    alpha2: CountriesAlpha3.AIA,
    currency: [CurrenciesEnum.XCD],
    name: CountriesFullName.AIA,
  },
  [CountriesAlpha3.ALA]: {
    alpha3: CountriesAlpha3.ALA,
    alpha2: CountriesAlpha3.ALA,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.ALA,
  },
  [CountriesAlpha3.ALB]: {
    alpha3: CountriesAlpha3.ALB,
    alpha2: CountriesAlpha3.ALB,
    currency: [CurrenciesEnum.ALL],
    name: CountriesFullName.ALB,
  },
  [CountriesAlpha3.AND]: {
    alpha3: CountriesAlpha3.AND,
    alpha2: CountriesAlpha3.AND,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.AND,
  },
  [CountriesAlpha3.ARE]: {
    alpha3: CountriesAlpha3.ARE,
    alpha2: CountriesAlpha3.ARE,
    currency: [CurrenciesEnum.AED],
    name: CountriesFullName.ARE,
  },
  [CountriesAlpha3.ARG]: {
    alpha3: CountriesAlpha3.ARG,
    alpha2: CountriesAlpha3.ARG,
    currency: [CurrenciesEnum.ARS],
    name: CountriesFullName.ARG,
  },
  [CountriesAlpha3.ARM]: {
    alpha3: CountriesAlpha3.ARM,
    alpha2: CountriesAlpha3.ARM,
    currency: [CurrenciesEnum.AMD],
    name: CountriesFullName.ARM,
  },
  [CountriesAlpha3.ASM]: {
    alpha3: CountriesAlpha3.ASM,
    alpha2: CountriesAlpha3.ASM,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.ASM,
  },
  [CountriesAlpha3.ATA]: {
    alpha3: CountriesAlpha3.ATA,
    alpha2: CountriesAlpha3.ATA,
    currency: [],
    name: CountriesFullName.ATA,
  },
  [CountriesAlpha3.ATF]: {
    alpha3: CountriesAlpha3.ATF,
    alpha2: CountriesAlpha3.ATF,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.ATF,
  },
  [CountriesAlpha3.ATG]: {
    alpha3: CountriesAlpha3.ATG,
    alpha2: CountriesAlpha3.ATG,
    currency: [CurrenciesEnum.XCD],
    name: CountriesFullName.ATG,
  },
  [CountriesAlpha3.AUS]: {
    alpha3: CountriesAlpha3.AUS,
    alpha2: CountriesAlpha3.AUS,
    currency: [CurrenciesEnum.AUD],
    name: CountriesFullName.AUS,
  },
  [CountriesAlpha3.AUT]: {
    alpha3: CountriesAlpha3.AUT,
    alpha2: CountriesAlpha3.AUT,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.AUT,
  },
  [CountriesAlpha3.AZE]: {
    alpha3: CountriesAlpha3.AZE,
    alpha2: CountriesAlpha3.AZE,
    currency: [CurrenciesEnum.AZN],
    name: CountriesFullName.AZE,
  },
  [CountriesAlpha3.BDI]: {
    alpha3: CountriesAlpha3.BDI,
    alpha2: CountriesAlpha3.BDI,
    currency: [CurrenciesEnum.BIF],
    name: CountriesFullName.BDI,
  },
  [CountriesAlpha3.BEL]: {
    alpha3: CountriesAlpha3.BEL,
    alpha2: CountriesAlpha3.BEL,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.BEL,
  },
  [CountriesAlpha3.BEN]: {
    alpha3: CountriesAlpha3.BEN,
    alpha2: CountriesAlpha3.BEN,
    currency: [CurrenciesEnum.XOF],
    name: CountriesFullName.BEN,
  },
  [CountriesAlpha3.BES]: {
    alpha3: CountriesAlpha3.BES,
    alpha2: CountriesAlpha3.BES,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.BES,
  },
  [CountriesAlpha3.BFA]: {
    alpha3: CountriesAlpha3.BFA,
    alpha2: CountriesAlpha3.BFA,
    currency: [CurrenciesEnum.XOF],
    name: CountriesFullName.BFA,
  },
  [CountriesAlpha3.BGD]: {
    alpha3: CountriesAlpha3.BGD,
    alpha2: CountriesAlpha3.BGD,
    currency: [CurrenciesEnum.BDT],
    name: CountriesFullName.BGD,
  },
  [CountriesAlpha3.BGR]: {
    alpha3: CountriesAlpha3.BGR,
    alpha2: CountriesAlpha3.BGR,
    currency: [CurrenciesEnum.BGN],
    name: CountriesFullName.BGR,
  },
  [CountriesAlpha3.BHR]: {
    alpha3: CountriesAlpha3.BHR,
    alpha2: CountriesAlpha3.BHR,
    currency: [CurrenciesEnum.BHD],
    name: CountriesFullName.BHR,
  },
  [CountriesAlpha3.BHS]: {
    alpha3: CountriesAlpha3.BHS,
    alpha2: CountriesAlpha3.BHS,
    currency: [CurrenciesEnum.BSD],
    name: CountriesFullName.BHS,
  },
  [CountriesAlpha3.BIH]: {
    alpha3: CountriesAlpha3.BIH,
    alpha2: CountriesAlpha3.BIH,
    currency: [CurrenciesEnum.BAM],
    name: CountriesFullName.BIH,
  },
  [CountriesAlpha3.BLM]: {
    alpha3: CountriesAlpha3.BLM,
    alpha2: CountriesAlpha3.BLM,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.BLM,
  },
  [CountriesAlpha3.BLR]: {
    alpha3: CountriesAlpha3.BLR,
    alpha2: CountriesAlpha3.BLR,
    currency: [CurrenciesEnum.BYN],
    name: CountriesFullName.BLR,
  },
  [CountriesAlpha3.BLZ]: {
    alpha3: CountriesAlpha3.BLZ,
    alpha2: CountriesAlpha3.BLZ,
    currency: [CurrenciesEnum.BZD],
    name: CountriesFullName.BLZ,
  },
  [CountriesAlpha3.BMU]: {
    alpha3: CountriesAlpha3.BMU,
    alpha2: CountriesAlpha3.BMU,
    currency: [CurrenciesEnum.BMD],
    name: CountriesFullName.BMU,
  },
  [CountriesAlpha3.BOL]: {
    alpha3: CountriesAlpha3.BOL,
    alpha2: CountriesAlpha3.BOL,
    currency: [CurrenciesEnum.BOB, CurrenciesEnum.BOV],
    name: CountriesFullName.BOL,
  },
  [CountriesAlpha3.BRA]: {
    alpha3: CountriesAlpha3.BRA,
    alpha2: CountriesAlpha3.BRA,
    currency: [CurrenciesEnum.BRL],
    name: CountriesFullName.BRA,
  },
  [CountriesAlpha3.BRB]: {
    alpha3: CountriesAlpha3.BRB,
    alpha2: CountriesAlpha3.BRB,
    currency: [CurrenciesEnum.BBD],
    name: CountriesFullName.BRB,
  },
  [CountriesAlpha3.BRN]: {
    alpha3: CountriesAlpha3.BRN,
    alpha2: CountriesAlpha3.BRN,
    currency: [CurrenciesEnum.BND],
    name: CountriesFullName.BRN,
  },
  [CountriesAlpha3.BTN]: {
    alpha3: CountriesAlpha3.BTN,
    alpha2: CountriesAlpha3.BTN,
    currency: [CurrenciesEnum.BTN, CurrenciesEnum.INR],
    name: CountriesFullName.BTN,
  },
  [CountriesAlpha3.BVT]: {
    alpha3: CountriesAlpha3.BVT,
    alpha2: CountriesAlpha3.BVT,
    currency: [CurrenciesEnum.NOK],
    name: CountriesFullName.BVT,
  },
  [CountriesAlpha3.BWA]: {
    alpha3: CountriesAlpha3.BWA,
    alpha2: CountriesAlpha3.BWA,
    currency: [CurrenciesEnum.BWP],
    name: CountriesFullName.BWA,
  },
  [CountriesAlpha3.CAF]: {
    alpha3: CountriesAlpha3.CAF,
    alpha2: CountriesAlpha3.CAF,
    currency: [CurrenciesEnum.XAF],
    name: CountriesFullName.CAF,
  },
  [CountriesAlpha3.CAN]: {
    alpha3: CountriesAlpha3.CAN,
    alpha2: CountriesAlpha3.CAN,
    currency: [CurrenciesEnum.CAD],
    name: CountriesFullName.CAN,
  },
  [CountriesAlpha3.CCK]: {
    alpha3: CountriesAlpha3.CCK,
    alpha2: CountriesAlpha3.CCK,
    currency: [CurrenciesEnum.AUD],
    name: CountriesFullName.CCK,
  },
  [CountriesAlpha3.CHE]: {
    alpha3: CountriesAlpha3.CHE,
    alpha2: CountriesAlpha3.CHE,
    currency: [CurrenciesEnum.CHE, CurrenciesEnum.CHF, CurrenciesEnum.CHW],
    name: CountriesFullName.CHE,
  },
  [CountriesAlpha3.CHL]: {
    alpha3: CountriesAlpha3.CHL,
    alpha2: CountriesAlpha3.CHL,
    currency: [CurrenciesEnum.CLF, CurrenciesEnum.CLP],
    name: CountriesFullName.CHL,
  },
  [CountriesAlpha3.CHN]: {
    alpha3: CountriesAlpha3.CHN,
    alpha2: CountriesAlpha3.CHN,
    currency: [CurrenciesEnum.CNY],
    name: CountriesFullName.CHN,
  },
  [CountriesAlpha3.CIV]: {
    alpha3: CountriesAlpha3.CIV,
    alpha2: CountriesAlpha3.CIV,
    currency: [CurrenciesEnum.XOF],
    name: CountriesFullName.CIV,
  },
  [CountriesAlpha3.CMR]: {
    alpha3: CountriesAlpha3.CMR,
    alpha2: CountriesAlpha3.CMR,
    currency: [CurrenciesEnum.XAF],
    name: CountriesFullName.CMR,
  },
  [CountriesAlpha3.COD]: {
    alpha3: CountriesAlpha3.COD,
    alpha2: CountriesAlpha3.COD,
    currency: [CurrenciesEnum.CDF],
    name: CountriesFullName.COD,
  },
  [CountriesAlpha3.COG]: {
    alpha3: CountriesAlpha3.COG,
    alpha2: CountriesAlpha3.COG,
    currency: [CurrenciesEnum.XAF],
    name: CountriesFullName.COG,
  },
  [CountriesAlpha3.COK]: {
    alpha3: CountriesAlpha3.COK,
    alpha2: CountriesAlpha3.COK,
    currency: [CurrenciesEnum.NZD],
    name: CountriesFullName.COK,
  },
  [CountriesAlpha3.COL]: {
    alpha3: CountriesAlpha3.COL,
    alpha2: CountriesAlpha3.COL,
    currency: [CurrenciesEnum.COP, CurrenciesEnum.COU],
    name: CountriesFullName.COL,
  },
  [CountriesAlpha3.COM]: {
    alpha3: CountriesAlpha3.COM,
    alpha2: CountriesAlpha3.COM,
    currency: [CurrenciesEnum.KMF],
    name: CountriesFullName.COM,
  },
  [CountriesAlpha3.CPV]: {
    alpha3: CountriesAlpha3.CPV,
    alpha2: CountriesAlpha3.CPV,
    currency: [CurrenciesEnum.CVE],
    name: CountriesFullName.CPV,
  },
  [CountriesAlpha3.CRI]: {
    alpha3: CountriesAlpha3.CRI,
    alpha2: CountriesAlpha3.CRI,
    currency: [CurrenciesEnum.CRC],
    name: CountriesFullName.CRI,
  },
  [CountriesAlpha3.CUB]: {
    alpha3: CountriesAlpha3.CUB,
    alpha2: CountriesAlpha3.CUB,
    currency: [CurrenciesEnum.CUP],
    name: CountriesFullName.CUB,
  },
  [CountriesAlpha3.CUW]: {
    alpha3: CountriesAlpha3.CUW,
    alpha2: CountriesAlpha3.CUW,
    currency: [CurrenciesEnum.ANG],
    name: CountriesFullName.CUW,
  },
  [CountriesAlpha3.CXR]: {
    alpha3: CountriesAlpha3.CXR,
    alpha2: CountriesAlpha3.CXR,
    currency: [CurrenciesEnum.AUD],
    name: CountriesFullName.CXR,
  },
  [CountriesAlpha3.CYM]: {
    alpha3: CountriesAlpha3.CYM,
    alpha2: CountriesAlpha3.CYM,
    currency: [CurrenciesEnum.KYD],
    name: CountriesFullName.CYM,
  },
  [CountriesAlpha3.CYP]: {
    alpha3: CountriesAlpha3.CYP,
    alpha2: CountriesAlpha3.CYP,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.CYP,
  },
  [CountriesAlpha3.CZE]: {
    alpha3: CountriesAlpha3.CZE,
    alpha2: CountriesAlpha3.CZE,
    currency: [CurrenciesEnum.CZK],
    name: CountriesFullName.CZE,
  },
  [CountriesAlpha3.DEU]: {
    alpha3: CountriesAlpha3.DEU,
    alpha2: CountriesAlpha3.DEU,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.DEU,
  },
  [CountriesAlpha3.DJI]: {
    alpha3: CountriesAlpha3.DJI,
    alpha2: CountriesAlpha3.DJI,
    currency: [CurrenciesEnum.DJF],
    name: CountriesFullName.DJI,
  },
  [CountriesAlpha3.DMA]: {
    alpha3: CountriesAlpha3.DMA,
    alpha2: CountriesAlpha3.DMA,
    currency: [CurrenciesEnum.XCD],
    name: CountriesFullName.DMA,
  },
  [CountriesAlpha3.DNK]: {
    alpha3: CountriesAlpha3.DNK,
    alpha2: CountriesAlpha3.DNK,
    currency: [CurrenciesEnum.DKK],
    name: CountriesFullName.DNK,
  },
  [CountriesAlpha3.DOM]: {
    alpha3: CountriesAlpha3.DOM,
    alpha2: CountriesAlpha3.DOM,
    currency: [CurrenciesEnum.DOP],
    name: CountriesFullName.DOM,
  },
  [CountriesAlpha3.DZA]: {
    alpha3: CountriesAlpha3.DZA,
    alpha2: CountriesAlpha3.DZA,
    currency: [CurrenciesEnum.DZD],
    name: CountriesFullName.DZA,
  },
  [CountriesAlpha3.ECU]: {
    alpha3: CountriesAlpha3.ECU,
    alpha2: CountriesAlpha3.ECU,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.ECU,
  },
  [CountriesAlpha3.EGY]: {
    alpha3: CountriesAlpha3.EGY,
    alpha2: CountriesAlpha3.EGY,
    currency: [CurrenciesEnum.EGP],
    name: CountriesFullName.EGY,
  },
  [CountriesAlpha3.ERI]: {
    alpha3: CountriesAlpha3.ERI,
    alpha2: CountriesAlpha3.ERI,
    currency: [CurrenciesEnum.ERN],
    name: CountriesFullName.ERI,
  },
  [CountriesAlpha3.ESH]: {
    alpha3: CountriesAlpha3.ESH,
    alpha2: CountriesAlpha3.ESH,
    currency: [CurrenciesEnum.MAD],
    name: CountriesFullName.ESH,
  },
  [CountriesAlpha3.ESP]: {
    alpha3: CountriesAlpha3.ESP,
    alpha2: CountriesAlpha3.ESP,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.ESP,
  },
  [CountriesAlpha3.EST]: {
    alpha3: CountriesAlpha3.EST,
    alpha2: CountriesAlpha3.EST,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.EST,
  },
  [CountriesAlpha3.ETH]: {
    alpha3: CountriesAlpha3.ETH,
    alpha2: CountriesAlpha3.ETH,
    currency: [CurrenciesEnum.ETB],
    name: CountriesFullName.ETH,
  },
  [CountriesAlpha3.FIN]: {
    alpha3: CountriesAlpha3.FIN,
    alpha2: CountriesAlpha3.FIN,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.FIN,
  },
  [CountriesAlpha3.FJI]: {
    alpha3: CountriesAlpha3.FJI,
    alpha2: CountriesAlpha3.FJI,
    currency: [CurrenciesEnum.FJD],
    name: CountriesFullName.FJI,
  },
  [CountriesAlpha3.FLK]: {
    alpha3: CountriesAlpha3.FLK,
    alpha2: CountriesAlpha3.FLK,
    currency: [CurrenciesEnum.FKP],
    name: CountriesFullName.FLK,
  },
  [CountriesAlpha3.FRA]: {
    alpha3: CountriesAlpha3.FRA,
    alpha2: CountriesAlpha3.FRA,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.FRA,
  },
  [CountriesAlpha3.FRO]: {
    alpha3: CountriesAlpha3.FRO,
    alpha2: CountriesAlpha3.FRO,
    currency: [CurrenciesEnum.DKK],
    name: CountriesFullName.FRO,
  },
  [CountriesAlpha3.FSM]: {
    alpha3: CountriesAlpha3.FSM,
    alpha2: CountriesAlpha3.FSM,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.FSM,
  },
  [CountriesAlpha3.GAB]: {
    alpha3: CountriesAlpha3.GAB,
    alpha2: CountriesAlpha3.GAB,
    currency: [CurrenciesEnum.XAF],
    name: CountriesFullName.GAB,
  },
  [CountriesAlpha3.GBR]: {
    alpha3: CountriesAlpha3.GBR,
    alpha2: CountriesAlpha3.GBR,
    currency: [CurrenciesEnum.GBP],
    name: CountriesFullName.GBR,
  },
  [CountriesAlpha3.GEO]: {
    alpha3: CountriesAlpha3.GEO,
    alpha2: CountriesAlpha3.GEO,
    currency: [CurrenciesEnum.GEL],
    name: CountriesFullName.GEO,
  },
  [CountriesAlpha3.GGY]: {
    alpha3: CountriesAlpha3.GGY,
    alpha2: CountriesAlpha3.GGY,
    currency: [CurrenciesEnum.GBP],
    name: CountriesFullName.GGY,
  },
  [CountriesAlpha3.GHA]: {
    alpha3: CountriesAlpha3.GHA,
    alpha2: CountriesAlpha3.GHA,
    currency: [CurrenciesEnum.GHS],
    name: CountriesFullName.GHA,
  },
  [CountriesAlpha3.GIB]: {
    alpha3: CountriesAlpha3.GIB,
    alpha2: CountriesAlpha3.GIB,
    currency: [CurrenciesEnum.GIP],
    name: CountriesFullName.GIB,
  },
  [CountriesAlpha3.GIN]: {
    alpha3: CountriesAlpha3.GIN,
    alpha2: CountriesAlpha3.GIN,
    currency: [CurrenciesEnum.GNF],
    name: CountriesFullName.GIN,
  },
  [CountriesAlpha3.GLP]: {
    alpha3: CountriesAlpha3.GLP,
    alpha2: CountriesAlpha3.GLP,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.GLP,
  },
  [CountriesAlpha3.GMB]: {
    alpha3: CountriesAlpha3.GMB,
    alpha2: CountriesAlpha3.GMB,
    currency: [CurrenciesEnum.GMD],
    name: CountriesFullName.GMB,
  },
  [CountriesAlpha3.GNB]: {
    alpha3: CountriesAlpha3.GNB,
    alpha2: CountriesAlpha3.GNB,
    currency: [CurrenciesEnum.XOF],
    name: CountriesFullName.GNB,
  },
  [CountriesAlpha3.GNQ]: {
    alpha3: CountriesAlpha3.GNQ,
    alpha2: CountriesAlpha3.GNQ,
    currency: [CurrenciesEnum.XAF],
    name: CountriesFullName.GNQ,
  },
  [CountriesAlpha3.GRC]: {
    alpha3: CountriesAlpha3.GRC,
    alpha2: CountriesAlpha3.GRC,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.GRC,
  },
  [CountriesAlpha3.GRD]: {
    alpha3: CountriesAlpha3.GRD,
    alpha2: CountriesAlpha3.GRD,
    currency: [CurrenciesEnum.XCD],
    name: CountriesFullName.GRD,
  },
  [CountriesAlpha3.GRL]: {
    alpha3: CountriesAlpha3.GRL,
    alpha2: CountriesAlpha3.GRL,
    currency: [CurrenciesEnum.DKK],
    name: CountriesFullName.GRL,
  },
  [CountriesAlpha3.GTM]: {
    alpha3: CountriesAlpha3.GTM,
    alpha2: CountriesAlpha3.GTM,
    currency: [CurrenciesEnum.GTQ],
    name: CountriesFullName.GTM,
  },
  [CountriesAlpha3.GUF]: {
    alpha3: CountriesAlpha3.GUF,
    alpha2: CountriesAlpha3.GUF,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.GUF,
  },
  [CountriesAlpha3.GUM]: {
    alpha3: CountriesAlpha3.GUM,
    alpha2: CountriesAlpha3.GUM,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.GUM,
  },
  [CountriesAlpha3.GUY]: {
    alpha3: CountriesAlpha3.GUY,
    alpha2: CountriesAlpha3.GUY,
    currency: [CurrenciesEnum.GYD],
    name: CountriesFullName.GUY,
  },
  [CountriesAlpha3.HKG]: {
    alpha3: CountriesAlpha3.HKG,
    alpha2: CountriesAlpha3.HKG,
    currency: [CurrenciesEnum.HKD],
    name: CountriesFullName.HKG,
  },
  [CountriesAlpha3.HMD]: {
    alpha3: CountriesAlpha3.HMD,
    alpha2: CountriesAlpha3.HMD,
    currency: [CurrenciesEnum.AUD],
    name: CountriesFullName.HMD,
  },
  [CountriesAlpha3.HND]: {
    alpha3: CountriesAlpha3.HND,
    alpha2: CountriesAlpha3.HND,
    currency: [CurrenciesEnum.HNL],
    name: CountriesFullName.HND,
  },
  [CountriesAlpha3.HRV]: {
    alpha3: CountriesAlpha3.HRV,
    alpha2: CountriesAlpha3.HRV,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.HRV,
  },
  [CountriesAlpha3.HTI]: {
    alpha3: CountriesAlpha3.HTI,
    alpha2: CountriesAlpha3.HTI,
    currency: [CurrenciesEnum.HTG],
    name: CountriesFullName.HTI,
  },
  [CountriesAlpha3.HUN]: {
    alpha3: CountriesAlpha3.HUN,
    alpha2: CountriesAlpha3.HUN,
    currency: [CurrenciesEnum.HUF],
    name: CountriesFullName.HUN,
  },
  [CountriesAlpha3.IDN]: {
    alpha3: CountriesAlpha3.IDN,
    alpha2: CountriesAlpha3.IDN,
    currency: [CurrenciesEnum.IDR],
    name: CountriesFullName.IDN,
  },
  [CountriesAlpha3.IMN]: {
    alpha3: CountriesAlpha3.IMN,
    alpha2: CountriesAlpha3.IMN,
    currency: [CurrenciesEnum.GBP],
    name: CountriesFullName.IMN,
  },
  [CountriesAlpha3.IND]: {
    alpha3: CountriesAlpha3.IND,
    alpha2: CountriesAlpha3.IND,
    currency: [CurrenciesEnum.INR],
    name: CountriesFullName.IND,
  },
  [CountriesAlpha3.IOT]: {
    alpha3: CountriesAlpha3.IOT,
    alpha2: CountriesAlpha3.IOT,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.IOT,
  },
  [CountriesAlpha3.IRL]: {
    alpha3: CountriesAlpha3.IRL,
    alpha2: CountriesAlpha3.IRL,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.IRL,
  },
  [CountriesAlpha3.IRN]: {
    alpha3: CountriesAlpha3.IRN,
    alpha2: CountriesAlpha3.IRN,
    currency: [CurrenciesEnum.IRR],
    name: CountriesFullName.IRN,
  },
  [CountriesAlpha3.IRQ]: {
    alpha3: CountriesAlpha3.IRQ,
    alpha2: CountriesAlpha3.IRQ,
    currency: [CurrenciesEnum.IQD],
    name: CountriesFullName.IRQ,
  },
  [CountriesAlpha3.ISL]: {
    alpha3: CountriesAlpha3.ISL,
    alpha2: CountriesAlpha3.ISL,
    currency: [CurrenciesEnum.ISK],
    name: CountriesFullName.ISL,
  },
  [CountriesAlpha3.ISR]: {
    alpha3: CountriesAlpha3.ISR,
    alpha2: CountriesAlpha3.ISR,
    currency: [CurrenciesEnum.ILS],
    name: CountriesFullName.ISR,
  },
  [CountriesAlpha3.ITA]: {
    alpha3: CountriesAlpha3.ITA,
    alpha2: CountriesAlpha3.ITA,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.ITA,
  },
  [CountriesAlpha3.JAM]: {
    alpha3: CountriesAlpha3.JAM,
    alpha2: CountriesAlpha3.JAM,
    currency: [CurrenciesEnum.JMD],
    name: CountriesFullName.JAM,
  },
  [CountriesAlpha3.JEY]: {
    alpha3: CountriesAlpha3.JEY,
    alpha2: CountriesAlpha3.JEY,
    currency: [CurrenciesEnum.GBP],
    name: CountriesFullName.JEY,
  },
  [CountriesAlpha3.JOR]: {
    alpha3: CountriesAlpha3.JOR,
    alpha2: CountriesAlpha3.JOR,
    currency: [CurrenciesEnum.JOD],
    name: CountriesFullName.JOR,
  },
  [CountriesAlpha3.JPN]: {
    alpha3: CountriesAlpha3.JPN,
    alpha2: CountriesAlpha3.JPN,
    currency: [CurrenciesEnum.JPY],
    name: CountriesFullName.JPN,
  },
  [CountriesAlpha3.KAZ]: {
    alpha3: CountriesAlpha3.KAZ,
    alpha2: CountriesAlpha3.KAZ,
    currency: [CurrenciesEnum.KZT],
    name: CountriesFullName.KAZ,
  },
  [CountriesAlpha3.KEN]: {
    alpha3: CountriesAlpha3.KEN,
    alpha2: CountriesAlpha3.KEN,
    currency: [CurrenciesEnum.KES],
    name: CountriesFullName.KEN,
  },
  [CountriesAlpha3.KGZ]: {
    alpha3: CountriesAlpha3.KGZ,
    alpha2: CountriesAlpha3.KGZ,
    currency: [CurrenciesEnum.KGS],
    name: CountriesFullName.KGZ,
  },
  [CountriesAlpha3.KHM]: {
    alpha3: CountriesAlpha3.KHM,
    alpha2: CountriesAlpha3.KHM,
    currency: [CurrenciesEnum.KHR],
    name: CountriesFullName.KHM,
  },
  [CountriesAlpha3.KIR]: {
    alpha3: CountriesAlpha3.KIR,
    alpha2: CountriesAlpha3.KIR,
    currency: [CurrenciesEnum.AUD],
    name: CountriesFullName.KIR,
  },
  [CountriesAlpha3.KNA]: {
    alpha3: CountriesAlpha3.COM,
    alpha2: CountriesAlpha3.COM,
    currency: [CurrenciesEnum.XCD],
    name: CountriesFullName.KNA,
  },
  [CountriesAlpha3.KOR]: {
    alpha3: CountriesAlpha3.KOR,
    alpha2: CountriesAlpha3.KOR,
    currency: [CurrenciesEnum.KPW],
    name: CountriesFullName.KOR,
  },
  [CountriesAlpha3.KWT]: {
    alpha3: CountriesAlpha3.KWT,
    alpha2: CountriesAlpha3.KWT,
    currency: [CurrenciesEnum.KWD],
    name: CountriesFullName.KWT,
  },
  [CountriesAlpha3.LAO]: {
    alpha3: CountriesAlpha3.LAO,
    alpha2: CountriesAlpha3.LAO,
    currency: [CurrenciesEnum.LAK],
    name: CountriesFullName.LAO,
  },
  [CountriesAlpha3.LBN]: {
    alpha3: CountriesAlpha3.LBN,
    alpha2: CountriesAlpha3.LBN,
    currency: [CurrenciesEnum.LBP],
    name: CountriesFullName.LBN,
  },
  [CountriesAlpha3.LBR]: {
    alpha3: CountriesAlpha3.LBR,
    alpha2: CountriesAlpha3.LBR,
    currency: [CurrenciesEnum.LRD],
    name: CountriesFullName.LBR,
  },
  [CountriesAlpha3.LBY]: {
    alpha3: CountriesAlpha3.LBY,
    alpha2: CountriesAlpha3.LBY,
    currency: [CurrenciesEnum.LYD],
    name: CountriesFullName.LBY,
  },
  [CountriesAlpha3.LCA]: {
    alpha3: CountriesAlpha3.LCA,
    alpha2: CountriesAlpha3.LCA,
    currency: [CurrenciesEnum.XCD],
    name: CountriesFullName.LCA,
  },
  [CountriesAlpha3.LIE]: {
    alpha3: CountriesAlpha3.LIE,
    alpha2: CountriesAlpha3.LIE,
    currency: [CurrenciesEnum.CHF],
    name: CountriesFullName.LIE,
  },
  [CountriesAlpha3.LKA]: {
    alpha3: CountriesAlpha3.LKA,
    alpha2: CountriesAlpha3.LKA,
    currency: [CurrenciesEnum.LKR],
    name: CountriesFullName.LKA,
  },
  [CountriesAlpha3.LSO]: {
    alpha3: CountriesAlpha3.LSO,
    alpha2: CountriesAlpha3.LSO,
    currency: [CurrenciesEnum.LSL],
    name: CountriesFullName.LSO,
  },
  [CountriesAlpha3.LTU]: {
    alpha3: CountriesAlpha3.COM,
    alpha2: CountriesAlpha3.COM,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.LTU,
  },
  [CountriesAlpha3.LUX]: {
    alpha3: CountriesAlpha3.LUX,
    alpha2: CountriesAlpha3.LUX,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.LUX,
  },
  [CountriesAlpha3.LVA]: {
    alpha3: CountriesAlpha3.LVA,
    alpha2: CountriesAlpha3.LVA,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.LVA,
  },
  [CountriesAlpha3.MAC]: {
    alpha3: CountriesAlpha3.MAC,
    alpha2: CountriesAlpha3.MAC,
    currency: [CurrenciesEnum.MOP],
    name: CountriesFullName.MAC,
  },
  [CountriesAlpha3.MAF]: {
    alpha3: CountriesAlpha3.MAF,
    alpha2: CountriesAlpha3.MAF,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.MAF,
  },
  [CountriesAlpha3.MAR]: {
    alpha3: CountriesAlpha3.MAR,
    alpha2: CountriesAlpha3.MAR,
    currency: [CurrenciesEnum.MAD],
    name: CountriesFullName.MAR,
  },
  [CountriesAlpha3.MCO]: {
    alpha3: CountriesAlpha3.MCO,
    alpha2: CountriesAlpha3.MCO,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.MCO,
  },
  [CountriesAlpha3.MDA]: {
    alpha3: CountriesAlpha3.MDA,
    alpha2: CountriesAlpha3.MDA,
    currency: [CurrenciesEnum.MDL],
    name: CountriesFullName.MDA,
  },
  [CountriesAlpha3.MDG]: {
    alpha3: CountriesAlpha3.MDG,
    alpha2: CountriesAlpha3.MDG,
    currency: [CurrenciesEnum.MGA],
    name: CountriesFullName.MDG,
  },
  [CountriesAlpha3.MDV]: {
    alpha3: CountriesAlpha3.MDV,
    alpha2: CountriesAlpha3.MDV,
    currency: [CurrenciesEnum.MVR],
    name: CountriesFullName.MDV,
  },
  [CountriesAlpha3.MEX]: {
    alpha3: CountriesAlpha3.MEX,
    alpha2: CountriesAlpha3.MEX,
    currency: [CurrenciesEnum.MXN, CurrenciesEnum.MXV],
    name: CountriesFullName.MEX,
  },
  [CountriesAlpha3.MHL]: {
    alpha3: CountriesAlpha3.MHL,
    alpha2: CountriesAlpha3.MHL,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.MHL,
  },
  [CountriesAlpha3.MKD]: {
    alpha3: CountriesAlpha3.MKD,
    alpha2: CountriesAlpha3.MKD,
    currency: [CurrenciesEnum.MKD],
    name: CountriesFullName.MKD,
  },
  [CountriesAlpha3.MLI]: {
    alpha3: CountriesAlpha3.MLI,
    alpha2: CountriesAlpha3.MLI,
    currency: [CurrenciesEnum.XOF],
    name: CountriesFullName.MLI,
  },
  [CountriesAlpha3.MLT]: {
    alpha3: CountriesAlpha3.MLT,
    alpha2: CountriesAlpha3.MLT,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.MLT,
  },
  [CountriesAlpha3.MMR]: {
    alpha3: CountriesAlpha3.MMR,
    alpha2: CountriesAlpha3.MMR,
    currency: [CurrenciesEnum.MMK],
    name: CountriesFullName.MMR,
  },
  [CountriesAlpha3.MNE]: {
    alpha3: CountriesAlpha3.MNE,
    alpha2: CountriesAlpha3.MNE,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.MNE,
  },
  [CountriesAlpha3.MNG]: {
    alpha3: CountriesAlpha3.MNG,
    alpha2: CountriesAlpha3.MNG,
    currency: [CurrenciesEnum.MNT],
    name: CountriesFullName.MNG,
  },
  [CountriesAlpha3.MNP]: {
    alpha3: CountriesAlpha3.MNP,
    alpha2: CountriesAlpha3.MNP,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.MNP,
  },
  [CountriesAlpha3.MOZ]: {
    alpha3: CountriesAlpha3.MOZ,
    alpha2: CountriesAlpha3.MOZ,
    currency: [CurrenciesEnum.MZN],
    name: CountriesFullName.MOZ,
  },
  [CountriesAlpha3.MRT]: {
    alpha3: CountriesAlpha3.MRT,
    alpha2: CountriesAlpha3.MRT,
    currency: [CurrenciesEnum.MRU],
    name: CountriesFullName.MRT,
  },
  [CountriesAlpha3.MSR]: {
    alpha3: CountriesAlpha3.MSR,
    alpha2: CountriesAlpha3.MSR,
    currency: [CurrenciesEnum.XCD],
    name: CountriesFullName.MSR,
  },
  [CountriesAlpha3.MTQ]: {
    alpha3: CountriesAlpha3.MTQ,
    alpha2: CountriesAlpha3.MTQ,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.MTQ,
  },
  [CountriesAlpha3.MUS]: {
    alpha3: CountriesAlpha3.MUS,
    alpha2: CountriesAlpha3.MUS,
    currency: [CurrenciesEnum.MUR],
    name: CountriesFullName.MUS,
  },
  [CountriesAlpha3.MWI]: {
    alpha3: CountriesAlpha3.MWI,
    alpha2: CountriesAlpha3.MWI,
    currency: [CurrenciesEnum.MWK],
    name: CountriesFullName.MWI,
  },
  [CountriesAlpha3.MYS]: {
    alpha3: CountriesAlpha3.MYS,
    alpha2: CountriesAlpha3.MYS,
    currency: [CurrenciesEnum.MYR],
    name: CountriesFullName.MYS,
  },
  [CountriesAlpha3.MYT]: {
    alpha3: CountriesAlpha3.MYT,
    alpha2: CountriesAlpha3.MYT,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.MYT,
  },
  [CountriesAlpha3.NAM]: {
    alpha3: CountriesAlpha3.NAM,
    alpha2: CountriesAlpha3.NAM,
    currency: [CurrenciesEnum.NAD],
    name: CountriesFullName.NAM,
  },
  [CountriesAlpha3.NCL]: {
    alpha3: CountriesAlpha3.NCL,
    alpha2: CountriesAlpha3.NCL,
    currency: [CurrenciesEnum.XPF],
    name: CountriesFullName.NCL,
  },
  [CountriesAlpha3.NER]: {
    alpha3: CountriesAlpha3.NER,
    alpha2: CountriesAlpha3.NER,
    currency: [CurrenciesEnum.XOF],
    name: CountriesFullName.NER,
  },
  [CountriesAlpha3.NFK]: {
    alpha3: CountriesAlpha3.NFK,
    alpha2: CountriesAlpha3.NFK,
    currency: [CurrenciesEnum.AUD],
    name: CountriesFullName.NFK,
  },
  [CountriesAlpha3.NGA]: {
    alpha3: CountriesAlpha3.NGA,
    alpha2: CountriesAlpha3.NGA,
    currency: [CurrenciesEnum.NGN],
    name: CountriesFullName.NGA,
  },
  [CountriesAlpha3.NIC]: {
    alpha3: CountriesAlpha3.NIC,
    alpha2: CountriesAlpha3.NIC,
    currency: [CurrenciesEnum.NIO],
    name: CountriesFullName.NIC,
  },
  [CountriesAlpha3.NIU]: {
    alpha3: CountriesAlpha3.NIU,
    alpha2: CountriesAlpha3.NIU,
    currency: [CurrenciesEnum.NZD],
    name: CountriesFullName.NIU,
  },
  [CountriesAlpha3.NLD]: {
    alpha3: CountriesAlpha3.NLD,
    alpha2: CountriesAlpha3.NLD,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.NLD,
  },
  [CountriesAlpha3.NOR]: {
    alpha3: CountriesAlpha3.NOR,
    alpha2: CountriesAlpha3.NOR,
    currency: [CurrenciesEnum.NOK],
    name: CountriesFullName.NOR,
  },
  [CountriesAlpha3.NPL]: {
    alpha3: CountriesAlpha3.NPL,
    alpha2: CountriesAlpha3.NPL,
    currency: [CurrenciesEnum.NPR],
    name: CountriesFullName.NPL,
  },
  [CountriesAlpha3.NRU]: {
    alpha3: CountriesAlpha3.NRU,
    alpha2: CountriesAlpha3.NRU,
    currency: [CurrenciesEnum.AUD],
    name: CountriesFullName.NRU,
  },
  [CountriesAlpha3.NZL]: {
    alpha3: CountriesAlpha3.NZL,
    alpha2: CountriesAlpha3.NZL,
    currency: [CurrenciesEnum.NZD],
    name: CountriesFullName.NZL,
  },
  [CountriesAlpha3.OMN]: {
    alpha3: CountriesAlpha3.OMN,
    alpha2: CountriesAlpha3.OMN,
    currency: [CurrenciesEnum.OMR],
    name: CountriesFullName.OMN,
  },
  [CountriesAlpha3.PAK]: {
    alpha3: CountriesAlpha3.PAK,
    alpha2: CountriesAlpha3.PAK,
    currency: [CurrenciesEnum.PKR],
    name: CountriesFullName.PAK,
  },
  [CountriesAlpha3.PAN]: {
    alpha3: CountriesAlpha3.PAN,
    alpha2: CountriesAlpha3.PAN,
    currency: [CurrenciesEnum.PAB],
    name: CountriesFullName.PAN,
  },
  [CountriesAlpha3.PCN]: {
    alpha3: CountriesAlpha3.PCN,
    alpha2: CountriesAlpha3.PCN,
    currency: [CurrenciesEnum.NZD],
    name: CountriesFullName.PCN,
  },
  [CountriesAlpha3.PER]: {
    alpha3: CountriesAlpha3.PER,
    alpha2: CountriesAlpha3.PER,
    currency: [CurrenciesEnum.PEN],
    name: CountriesFullName.PER,
  },
  [CountriesAlpha3.PHL]: {
    alpha3: CountriesAlpha3.PHL,
    alpha2: CountriesAlpha3.PHL,
    currency: [CurrenciesEnum.PHP],
    name: CountriesFullName.PHL,
  },
  [CountriesAlpha3.PLW]: {
    alpha3: CountriesAlpha3.PLW,
    alpha2: CountriesAlpha3.PLW,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.PLW,
  },
  [CountriesAlpha3.PNG]: {
    alpha3: CountriesAlpha3.PNG,
    alpha2: CountriesAlpha3.PNG,
    currency: [CurrenciesEnum.PGK],
    name: CountriesFullName.PNG,
  },
  [CountriesAlpha3.POL]: {
    alpha3: CountriesAlpha3.POL,
    alpha2: CountriesAlpha3.POL,
    currency: [CurrenciesEnum.PLN],
    name: CountriesFullName.POL,
  },
  [CountriesAlpha3.PRI]: {
    alpha3: CountriesAlpha3.PRI,
    alpha2: CountriesAlpha3.PRI,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.PRI,
  },
  [CountriesAlpha3.PRK]: {
    alpha3: CountriesAlpha3.PRK,
    alpha2: CountriesAlpha3.PRK,
    currency: [CurrenciesEnum.KRW],
    name: CountriesFullName.PRK,
  },
  [CountriesAlpha3.PRT]: {
    alpha3: CountriesAlpha3.PRT,
    alpha2: CountriesAlpha3.PRT,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.PRT,
  },
  [CountriesAlpha3.PRY]: {
    alpha3: CountriesAlpha3.PRY,
    alpha2: CountriesAlpha3.PRY,
    currency: [CurrenciesEnum.PYG],
    name: CountriesFullName.PRY,
  },
  [CountriesAlpha3.PSE]: {
    alpha3: CountriesAlpha3.PSE,
    alpha2: CountriesAlpha3.PSE,
    currency: [CurrenciesEnum.EGP, CurrenciesEnum.ILS, CurrenciesEnum.JOD],
    name: CountriesFullName.PSE,
  },
  [CountriesAlpha3.PYF]: {
    alpha3: CountriesAlpha3.PYF,
    alpha2: CountriesAlpha3.PYF,
    currency: [CurrenciesEnum.XPF],
    name: CountriesFullName.PYF,
  },
  [CountriesAlpha3.QAT]: {
    alpha3: CountriesAlpha3.QAT,
    alpha2: CountriesAlpha3.QAT,
    currency: [CurrenciesEnum.QAR],
    name: CountriesFullName.QAT,
  },
  [CountriesAlpha3.REU]: {
    alpha3: CountriesAlpha3.REU,
    alpha2: CountriesAlpha3.REU,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.REU,
  },
  [CountriesAlpha3.ROU]: {
    alpha3: CountriesAlpha3.ROU,
    alpha2: CountriesAlpha3.ROU,
    currency: [CurrenciesEnum.RON],
    name: CountriesFullName.ROU,
  },
  [CountriesAlpha3.RUS]: {
    alpha3: "Пидоры умрите",
    alpha2: "Пидоры умрите",
    currency: [CurrenciesEnum.RUB],
    name: CountriesFullName.RUS,
  },
  [CountriesAlpha3.RWA]: {
    alpha3: CountriesAlpha3.RWA,
    alpha2: CountriesAlpha3.RWA,
    currency: [CurrenciesEnum.RWF],
    name: CountriesFullName.RWA,
  },
  [CountriesAlpha3.SAU]: {
    alpha3: CountriesAlpha3.SAU,
    alpha2: CountriesAlpha3.SAU,
    currency: [CurrenciesEnum.SAR],
    name: CountriesFullName.SAU,
  },
  [CountriesAlpha3.SDN]: {
    alpha3: CountriesAlpha3.SDN,
    alpha2: CountriesAlpha3.SDN,
    currency: [CurrenciesEnum.SDG],
    name: CountriesFullName.SDN,
  },
  [CountriesAlpha3.SEN]: {
    alpha3: CountriesAlpha3.SEN,
    alpha2: CountriesAlpha3.SEN,
    currency: [CurrenciesEnum.XOF],
    name: CountriesFullName.SEN,
  },
  [CountriesAlpha3.SGP]: {
    alpha3: CountriesAlpha3.SGP,
    alpha2: CountriesAlpha3.SGP,
    currency: [CurrenciesEnum.SGD],
    name: CountriesFullName.SGP,
  },
  [CountriesAlpha3.SGS]: {
    alpha3: CountriesAlpha3.SGS,
    alpha2: CountriesAlpha3.SGS,
    currency: [CurrenciesEnum.FKP],
    name: CountriesFullName.SGS,
  },
  [CountriesAlpha3.SHN]: {
    alpha3: CountriesAlpha3.SHN,
    alpha2: CountriesAlpha3.SHN,
    currency: [CurrenciesEnum.SHP],
    name: CountriesFullName.SHN,
  },
  [CountriesAlpha3.SJM]: {
    alpha3: CountriesAlpha3.SJM,
    alpha2: CountriesAlpha3.SJM,
    currency: [CurrenciesEnum.NOK],
    name: CountriesFullName.SJM,
  },
  [CountriesAlpha3.SLB]: {
    alpha3: CountriesAlpha3.SLB,
    alpha2: CountriesAlpha3.SLB,
    currency: [CurrenciesEnum.SBD],
    name: CountriesFullName.SLB,
  },
  [CountriesAlpha3.SLE]: {
    alpha3: CountriesAlpha3.SLE,
    alpha2: CountriesAlpha3.SLE,
    currency: [CurrenciesEnum.SLE, CurrenciesEnum.SLL],
    name: CountriesFullName.SLE,
  },
  [CountriesAlpha3.SLV]: {
    alpha3: CountriesAlpha3.SLV,
    alpha2: CountriesAlpha3.SLV,
    currency: [CurrenciesEnum.SVC],
    name: CountriesFullName.SLV,
  },
  [CountriesAlpha3.SMR]: {
    alpha3: CountriesAlpha3.SMR,
    alpha2: CountriesAlpha3.SMR,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.SMR,
  },
  [CountriesAlpha3.SOM]: {
    alpha3: CountriesAlpha3.SOM,
    alpha2: CountriesAlpha3.SOM,
    currency: [CurrenciesEnum.SOS],
    name: CountriesFullName.SOM,
  },
  [CountriesAlpha3.SPM]: {
    alpha3: CountriesAlpha3.SPM,
    alpha2: CountriesAlpha3.SPM,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.SPM,
  },
  [CountriesAlpha3.SRB]: {
    alpha3: CountriesAlpha3.SRB,
    alpha2: CountriesAlpha3.SRB,
    currency: [CurrenciesEnum.RSD],
    name: CountriesFullName.SRB,
  },
  [CountriesAlpha3.SSD]: {
    alpha3: CountriesAlpha3.SSD,
    alpha2: CountriesAlpha3.SSD,
    currency: [CurrenciesEnum.SSP],
    name: CountriesFullName.SSD,
  },
  [CountriesAlpha3.STP]: {
    alpha3: CountriesAlpha3.STP,
    alpha2: CountriesAlpha3.STP,
    currency: [CurrenciesEnum.STN],
    name: CountriesFullName.STP,
  },
  [CountriesAlpha3.SUR]: {
    alpha3: CountriesAlpha3.SUR,
    alpha2: CountriesAlpha3.SUR,
    currency: [CurrenciesEnum.SRD],
    name: CountriesFullName.SUR,
  },
  [CountriesAlpha3.SVK]: {
    alpha3: CountriesAlpha3.SVK,
    alpha2: CountriesAlpha3.SVK,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.SVK,
  },
  [CountriesAlpha3.SVN]: {
    alpha3: CountriesAlpha3.SVN,
    alpha2: CountriesAlpha3.SVN,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.SVN,
  },
  [CountriesAlpha3.SWE]: {
    alpha3: CountriesAlpha3.SWE,
    alpha2: CountriesAlpha3.SWE,
    currency: [CurrenciesEnum.SEK],
    name: CountriesFullName.SWE,
  },
  [CountriesAlpha3.SWZ]: {
    alpha3: CountriesAlpha3.SWZ,
    alpha2: CountriesAlpha3.SWZ,
    currency: [CurrenciesEnum.SZL],
    name: CountriesFullName.SWZ,
  },
  [CountriesAlpha3.SXM]: {
    alpha3: CountriesAlpha3.SXM,
    alpha2: CountriesAlpha3.SXM,
    currency: [CurrenciesEnum.ANG],
    name: CountriesFullName.SXM,
  },
  [CountriesAlpha3.SYC]: {
    alpha3: CountriesAlpha3.SYC,
    alpha2: CountriesAlpha3.SYC,
    currency: [CurrenciesEnum.SCR],
    name: CountriesFullName.SYC,
  },
  [CountriesAlpha3.SYR]: {
    alpha3: CountriesAlpha3.SYR,
    alpha2: CountriesAlpha3.SYR,
    currency: [CurrenciesEnum.SYP],
    name: CountriesFullName.SYR,
  },
  [CountriesAlpha3.TCA]: {
    alpha3: CountriesAlpha3.TCA,
    alpha2: CountriesAlpha3.TCA,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.TCA,
  },
  [CountriesAlpha3.TCD]: {
    alpha3: CountriesAlpha3.TCD,
    alpha2: CountriesAlpha3.TCD,
    currency: [CurrenciesEnum.XAF],
    name: CountriesFullName.TCD,
  },
  [CountriesAlpha3.TGO]: {
    alpha3: CountriesAlpha3.TGO,
    alpha2: CountriesAlpha3.TGO,
    currency: [CurrenciesEnum.XOF],
    name: CountriesFullName.TGO,
  },
  [CountriesAlpha3.THA]: {
    alpha3: CountriesAlpha3.THA,
    alpha2: CountriesAlpha3.THA,
    currency: [CurrenciesEnum.THB],
    name: CountriesFullName.THA,
  },
  [CountriesAlpha3.TJK]: {
    alpha3: CountriesAlpha3.TJK,
    alpha2: CountriesAlpha3.TJK,
    currency: [CurrenciesEnum.TJS],
    name: CountriesFullName.TJK,
  },
  [CountriesAlpha3.TKL]: {
    alpha3: CountriesAlpha3.TKL,
    alpha2: CountriesAlpha3.TKL,
    currency: [CurrenciesEnum.NZD],
    name: CountriesFullName.TKL,
  },
  [CountriesAlpha3.TKM]: {
    alpha3: CountriesAlpha3.TKM,
    alpha2: CountriesAlpha3.TKM,
    currency: [CurrenciesEnum.TMT],
    name: CountriesFullName.TKM,
  },
  [CountriesAlpha3.TLS]: {
    alpha3: CountriesAlpha3.TLS,
    alpha2: CountriesAlpha3.TLS,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.TLS,
  },
  [CountriesAlpha3.TON]: {
    alpha3: CountriesAlpha3.TON,
    alpha2: CountriesAlpha3.TON,
    currency: [CurrenciesEnum.TOP],
    name: CountriesFullName.TON,
  },
  [CountriesAlpha3.TTO]: {
    alpha3: CountriesAlpha3.TTO,
    alpha2: CountriesAlpha3.TTO,
    currency: [CurrenciesEnum.TTD],
    name: CountriesFullName.TTO,
  },
  [CountriesAlpha3.TUN]: {
    alpha3: CountriesAlpha3.TUN,
    alpha2: CountriesAlpha3.TUN,
    currency: [CurrenciesEnum.TND],
    name: CountriesFullName.TUN,
  },
  [CountriesAlpha3.TUR]: {
    alpha3: CountriesAlpha3.TUR,
    alpha2: CountriesAlpha3.TUR,
    currency: [CurrenciesEnum.TRY],
    name: CountriesFullName.TUR,
  },
  [CountriesAlpha3.TUV]: {
    alpha3: CountriesAlpha3.TUV,
    alpha2: CountriesAlpha3.TUV,
    currency: [CurrenciesEnum.AUD],
    name: CountriesFullName.TUV,
  },
  [CountriesAlpha3.TWN]: {
    alpha3: CountriesAlpha3.TWN,
    alpha2: CountriesAlpha3.TWN,
    currency: [CurrenciesEnum.TWD],
    name: CountriesFullName.TWN,
  },
  [CountriesAlpha3.TZA]: {
    alpha3: CountriesAlpha3.TZA,
    alpha2: CountriesAlpha3.TZA,
    currency: [CurrenciesEnum.TZS],
    name: CountriesFullName.TZA,
  },
  [CountriesAlpha3.UGA]: {
    alpha3: CountriesAlpha3.UGA,
    alpha2: CountriesAlpha3.UGA,
    currency: [CurrenciesEnum.UGX],
    name: CountriesFullName.UGA,
  },
  [CountriesAlpha3.UKR]: {
    alpha3: CountriesAlpha3.UKR,
    alpha2: CountriesAlpha3.UKR,
    currency: [CurrenciesEnum.UAH],
    name: CountriesFullName.UKR,
  },
  [CountriesAlpha3.UMI]: {
    alpha3: CountriesAlpha3.UMI,
    alpha2: CountriesAlpha3.UMI,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.UMI,
  },
  [CountriesAlpha3.URY]: {
    alpha3: CountriesAlpha3.URY,
    alpha2: CountriesAlpha3.URY,
    currency: [CurrenciesEnum.UYI, CurrenciesEnum.UYU, CurrenciesEnum.UYW],
    name: CountriesFullName.URY,
  },
  [CountriesAlpha3.USA]: {
    alpha3: CountriesAlpha3.USA,
    alpha2: CountriesAlpha3.USA,
    currency: [CurrenciesEnum.USD, CurrenciesEnum.USN],
    name: CountriesFullName.USA,
  },
  [CountriesAlpha3.UZB]: {
    alpha3: CountriesAlpha3.UZB,
    alpha2: CountriesAlpha3.UZB,
    currency: [CurrenciesEnum.UZS],
    name: CountriesFullName.UZB,
  },
  [CountriesAlpha3.VAT]: {
    alpha3: CountriesAlpha3.VAT,
    alpha2: CountriesAlpha3.VAT,
    currency: [CurrenciesEnum.EUR],
    name: CountriesFullName.VAT,
  },
  [CountriesAlpha3.VCT]: {
    alpha3: CountriesAlpha3.VCT,
    alpha2: CountriesAlpha3.VCT,
    currency: [CurrenciesEnum.XCD],
    name: CountriesFullName.VCT,
  },
  [CountriesAlpha3.VEN]: {
    alpha3: CountriesAlpha3.VEN,
    alpha2: CountriesAlpha3.VEN,
    currency: [CurrenciesEnum.VED, CurrenciesEnum.VES],
    name: CountriesFullName.VEN,
  },
  [CountriesAlpha3.VGB]: {
    alpha3: CountriesAlpha3.VGB,
    alpha2: CountriesAlpha3.VGB,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.VGB,
  },
  [CountriesAlpha3.VIR]: {
    alpha3: CountriesAlpha3.VIR,
    alpha2: CountriesAlpha3.VIR,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.VIR,
  },
  [CountriesAlpha3.VNM]: {
    alpha3: CountriesAlpha3.VNM,
    alpha2: CountriesAlpha3.VNM,
    currency: [CurrenciesEnum.VND],
    name: CountriesFullName.VNM,
  },
  [CountriesAlpha3.VUT]: {
    alpha3: CountriesAlpha3.VUT,
    alpha2: CountriesAlpha3.VUT,
    currency: [CurrenciesEnum.VUV],
    name: CountriesFullName.VUT,
  },
  [CountriesAlpha3.WLF]: {
    alpha3: CountriesAlpha3.WLF,
    alpha2: CountriesAlpha3.WLF,
    currency: [CurrenciesEnum.XPF],
    name: CountriesFullName.WLF,
  },
  [CountriesAlpha3.WSM]: {
    alpha3: CountriesAlpha3.WSM,
    alpha2: CountriesAlpha3.WSM,
    currency: [CurrenciesEnum.USD],
    name: CountriesFullName.WSM,
  },
  [CountriesAlpha3.YEM]: {
    alpha3: CountriesAlpha3.YEM,
    alpha2: CountriesAlpha3.YEM,
    currency: [CurrenciesEnum.YER],
    name: CountriesFullName.YEM,
  },
  [CountriesAlpha3.ZAF]: {
    alpha3: CountriesAlpha3.ZAF,
    alpha2: CountriesAlpha3.ZAF,
    currency: [CurrenciesEnum.ZAR],
    name: CountriesFullName.ZAF,
  },
  [CountriesAlpha3.ZMB]: {
    alpha3: CountriesAlpha3.ZMB,
    alpha2: CountriesAlpha3.ZMB,
    currency: [CurrenciesEnum.ZMW],
    name: CountriesFullName.ZMB,
  },
  [CountriesAlpha3.ZWE]: {
    alpha3: CountriesAlpha3.ZWE,
    alpha2: CountriesAlpha3.ZWE,
    currency: [CurrenciesEnum.ZWL],
    name: CountriesFullName.ZWE,
  },
}
